# Generated by Django 4.1.4 on 2024-05-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0004_consolidatedusertransactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_id',
        ),
        migrations.AlterModelTable(
            name='transactions',
            table=None,
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
