# Generated by Django 4.1.4 on 2024-05-22 20:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0005_remove_transactions_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitems',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='user_id',
        ),
        migrations.AddField(
            model_name='transactionitems',
            name='transaction',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cubaapp.transactions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cubaapp.users'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='transactions',
            table='transactions',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
        migrations.CreateModel(
            name='UserPurchasedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubaapp.transactionitems')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubaapp.transactions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubaapp.users')),
            ],
            options={
                'db_table': 'user_purchased_items',
            },
        ),
    ]
