# Generated by Django 4.1.4 on 2024-05-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0006_remove_transactionitems_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transactionitems',
            index=models.Index(fields=['id'], name='transaction_id_3f25fe_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionitems',
            index=models.Index(fields=['transaction'], name='transaction_transac_163e28_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionitems',
            index=models.Index(fields=['product_id'], name='transaction_product_762b50_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionitems',
            index=models.Index(fields=['created_at'], name='transaction_created_3b2586_idx'),
        ),
        migrations.AddIndex(
            model_name='transactions',
            index=models.Index(fields=['id'], name='transaction_id_399ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='transactions',
            index=models.Index(fields=['user'], name='transaction_user_id_b5bcfd_idx'),
        ),
        migrations.AddIndex(
            model_name='transactions',
            index=models.Index(fields=['organization_id'], name='transaction_organiz_6c8e16_idx'),
        ),
        migrations.AddIndex(
            model_name='transactions',
            index=models.Index(fields=['operator_name'], name='transaction_operato_e4d657_idx'),
        ),
        migrations.AddIndex(
            model_name='transactions',
            index=models.Index(fields=['created_date'], name='transaction_created_3bbb60_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['id'], name='users_id_6a15a7_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['type'], name='users_type_6e04c6_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
    ]
