# Generated by Django 4.1.4 on 2024-05-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0007_transactionitems_transaction_id_3f25fe_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transactions',
            index=models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx'),
        ),
    ]
